apiVersion: v1
kind: Service
metadata:
  name: chipfire-backend
  namespace: pires
  labels:
    app.kubernetes.io/name: chipfire-backend
    app.kubernetes.io/part-of: chipfire
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chipfire-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
