apiVersion: v1
kind: Service
metadata:
  name: chipfire-redis
  namespace: pires
  labels:
    app.kubernetes.io/name: chipfire-redis
    app.kubernetes.io/part-of: chipfire
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chipfire-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
